@baseURL =  http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseURL}}/home/hello

### AppControllerExemplo

# @name AppControllerExemplo
GET {{baseURL}}/home/exemplo/

### ConceitosManualControllerHome

# @name ConceitosManualControllerHome
GET {{baseURL}}/conceitos-manual/

### ConceitosAutomaticoController

# @name ConceitosAutomaticoController
GET {{baseURL}}/conceitos-automatico/